// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	read_properties "github.com/skolldire/web-simplify/pkg/utilities/read_properties"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Apply provides a mock function with no fields
func (_m *Service) Apply() (read_properties.Config, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 read_properties.Config
	var r1 error
	if rf, ok := ret.Get(0).(func() (read_properties.Config, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() read_properties.Config); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(read_properties.Config)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
